// src/lib/Navbar.svelte
<nav class="navbar">
  <ul class="left">
    <li><a href="#">Home</a></li>
    <li><a href="#">Projects</a></li>
  </ul>
  <ul class="right">
    <li><a href="#">Contact</a></li>
  </ul>
</nav>

<style lang="scss">
  .navbar {
    padding: 30px;
    display: flex;
    justify-content: space-between;
  }

  ul {
    display: flex;
    gap: 20px;
    list-style: none;
    padding: 0;
    margin: 0;
  }

  a {
    text-decoration: none;
    color: inherit;
    padding: 10px;
  }
</style>

// src/components/Navbar.vue
<template>
  <nav class="navbar flex items-center justify-between p-5">
    <ul class="flex space-x-6">
      <li><a href="#">Home</a></li>
      <li><a href="#projects">Projects</a></li>
    </ul>
    <ul class="flex space-x-6">
      <li>
        <ContactButton />
      </li>
    </ul>
  </nav>
</template>

<script lang="ts" setup>
import ContactButton from "./ContactButton.vue";
</script>
